# Generated by Django 4.2.3 on 2023-09-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3)),
                ('currency_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'currencies',
            },
        ),
    ]
